"""Convert the vector GPCR tree (PDF) into js/data/tree.js and images/gpcrome_tree.svg.

Branches are grouped per class by their stroke colour; text in the PDF is ignored.

Usage: python tools/build_tree.py
"""
import json
from pathlib import Path

import pymupdf

ROOT = Path(__file__).resolve().parent.parent
PDF = ROOT / 'images' / 'GPCR_from_scratch_v8.pdf'

# Class order is also the drawing order (first = bottom).
CLASSES = [
    ('rhodopsin', 'Rhodopsin (class A)', (0.313, 0.501, 0.717)),
    ('rogues', 'Rhodopsin rogues', (0.544, 0.703, 0.877)),
    ('orphan', 'Orphan', (0.6, 0.597, 0.614)),
    ('adhesion', 'Adhesion (class B2)', (0.488, 0.229, 0.654)),
    ('secretin', 'Secretin (class B1)', (0.71, 0.235, 0.214)),
    ('glutamate', 'Glutamate (class C)', (0.953, 0.595, 0.255)),
    ('frizzled', 'Frizzled (class F)', (0.615, 0.787, 0.28)),
    ('tas2', 'Taste 2 (class T2)', (0.463, 0.593, 0.205)),
]
EXTRA_COLORS = {
    (0.251, 0.42, 0.659): 'rhodopsin',   # olfactory receptor arrow
    (0.513, 0.653, 0.229): 'tas2',       # trunk connector
}
DEFAULT_OPACITY = 0.75


def hex_color(rgb):
    return '#' + ''.join(f'{round(c * 255):02x}' for c in rgb)


def r(v):
    return round(v, 2)


def main():
    by_color = {c: cid for cid, _, c in CLASSES} | EXTRA_COLORS
    page = pymupdf.open(PDF)[0]
    tree = {
        'width': r(page.rect.width),
        'height': r(page.rect.height),
        'defaultOpacity': DEFAULT_OPACITY,
        'classes': [{'id': cid, 'name': name, 'color': hex_color(c)} for cid, name, c in CLASSES],
        'segments': {cid: [] for cid, _, _ in CLASSES},
        'paths': {cid: [] for cid, _, _ in CLASSES},
    }
    for d in page.get_drawings():
        rgb = d.get('color') if d['type'] == 's' else d.get('fill')
        cid = by_color.get(tuple(round(c, 3) for c in rgb or ()))
        if cid is None:
            continue
        items = d['items']
        opacity = d.get('stroke_opacity') or 1.0
        if d['type'] == 's' and len(items) == 1 and items[0][0] == 'l':
            a, b = items[0][1], items[0][2]
            seg = [r(a.x), r(a.y), r(b.x), r(b.y), r(d['width'])]
            if abs(opacity - DEFAULT_OPACITY) > 0.01:
                seg.append(r(opacity))
            tree['segments'][cid].append(seg)
            continue
        parts = [f'M{r(items[0][1].x)},{r(items[0][1].y)}']
        for it in items:
            if it[0] == 'l':
                parts.append(f'L{r(it[2].x)},{r(it[2].y)}')
            elif it[0] == 'c':
                parts.append('C' + ' '.join(f'{r(p.x)},{r(p.y)}' for p in it[2:5]))
        parts.append('Z')
        tree['paths'][cid].append({
            'd': ''.join(parts),
            'mode': 'stroke' if d['type'] == 's' else 'fill',
            'width': r(d.get('width') or 0),
            'opacity': r(opacity if d['type'] == 's' else d.get('fill_opacity') or 1.0),
        })

    out = ROOT / 'js' / 'data' / 'tree.js'
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text('/* Generated by tools/build_tree.py - do not edit by hand */\n'
                   f'window.GPCROME_TREE = {json.dumps(tree, separators=(",", ":"))};\n')

    svg = [f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 {tree["width"]} {tree["height"]}">',
           '<g stroke-linecap="round" fill="none">']
    for cls in tree['classes']:
        cid, col = cls['id'], cls['color']
        svg.append(f'<g id="class-{cid}" stroke="{col}">')
        for x1, y1, x2, y2, w, *op in tree['segments'][cid]:
            svg.append(f'<line x1="{x1}" y1="{y1}" x2="{x2}" y2="{y2}" stroke-width="{w}" '
                       f'stroke-opacity="{op[0] if op else DEFAULT_OPACITY}"/>')
        for p in tree['paths'][cid]:
            attr = (f'stroke-width="{p["width"]}" stroke-opacity="{p["opacity"]}"' if p['mode'] == 'stroke'
                    else f'stroke="none" fill="{col}" fill-opacity="{p["opacity"]}"')
            svg.append(f'<path d="{p["d"]}" {attr}/>')
        svg.append('</g>')
    svg.append('</g></svg>')
    (ROOT / 'images' / 'gpcrome_tree.svg').write_text('\n'.join(svg) + '\n')
    n = sum(len(v) for v in tree['segments'].values())
    print(f'{n} segments written to {out.relative_to(ROOT)} and images/gpcrome_tree.svg')


if __name__ == '__main__':
    main()
